// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    docsSidebar: [
        'introduction',
        'how_it_works',
        // 'theory',
        'development_boards',
        // {
        //     label: 'How to build',
        //     type: 'category',
        //     collapsed: true,
        //     items: [
        //         {
        //             type: 'autogenerated',
        //             dirName: 'build'
        //         }
        //     ]
        // }
        'contribution',
        'glossary',
        'faq',

    ]

};

module.exports = sidebars;
