// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    docsSidebar: [
        {
            type: 'doc',
            label: 'Introduction',
            id: 'introduction'
        },
        {
            type: 'category',
            label: 'Overview',
            items: 
            [
                {
                    type: 'autogenerated',
                    dirName: 'overview'
                }
            ]
        },
        {
            type: 'category',
            label: 'Develop stuff',
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'development'
                }
            ]
        },
        {
            type: 'category',
            label: 'Build (coming soon)',
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'build'
                }
            ]
        }
    ]

};

module.exports = sidebars;
