// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    docsSidebar: [
        'introduction',
        'how_it_works',
        'theory',
        {
            label: 'Development board',
            type: 'category',
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'devboard'
                }
            ]
        }
    ]

};

module.exports = sidebars;
